// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmQLQtmIj-s0Llm1xBH3WZXsPVLHkE36I',
    appId: '1:528777391195:web:661a6d187df269c12ae37e',
    messagingSenderId: '528777391195',
    projectId: 'laphic-app-modern-homes',
    authDomain: 'laphic-app-modern-homes.firebaseapp.com',
    storageBucket: 'laphic-app-modern-homes.firebasestorage.app',
    measurementId: 'G-QYQBZLHLYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBloBxKH3-tcdCVO5EM0PukSnkglEIDrmE',
    appId: '1:528777391195:android:b8ffa6d821f75cb22ae37e',
    messagingSenderId: '528777391195',
    projectId: 'laphic-app-modern-homes',
    storageBucket: 'laphic-app-modern-homes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUfo9J2nasVuojmYXb2OJP8V8cRIwL1M0',
    appId: '1:528777391195:ios:b6ff99bdeeb6d3552ae37e',
    messagingSenderId: '528777391195',
    projectId: 'laphic-app-modern-homes',
    storageBucket: 'laphic-app-modern-homes.firebasestorage.app',
    iosBundleId: 'com.example.laphicApp',
  );
}
